name: Bazel Build

on:
  pull_request:
  push:
    branches: main

env:
   DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer

jobs:
  macos:
    name: Bazel
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Test iOS
      run: bazelisk test //Tests:KronosTestsiOS --test_output=errors
    - name: Test MacOS
      run: bazelisk test //Tests:KronosTestsMacOS --test_output=errors
