name: Bazel Build

on: [pull_request]

env:
   DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

jobs:
  macos:
    name: Bazel
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test iOS
      run: bazelisk test //Tests:KronosTestsiOS --test_output=errors
    - name: Test MacOS
      run: bazelisk test //Tests:KronosTestsMacOS --test_output=errors
    - name: Test tvOS
      run: bazelisk test //Tests:KronosTestsTVOS --test_output=errors
